//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class A320_213_Param
    {
        public string MNEMONIC { get; set; }
        public string AGE_INDEX { get; set; }
        public int REC_WORD_NO { get; set; }
        public Nullable<int> REC_SUBFRAME { get; set; }
        public Nullable<int> REC_LSB { get; set; }
        public Nullable<int> REC_LEN { get; set; }
        public Nullable<bool> SIGNED { get; set; }
        public string COMMENT { get; set; }
        public string PARAM_NAME { get; set; }
        public string DATA_FORMAT { get; set; }
        public string CONV_TYPE { get; set; }
        public string CONV_FACTOR { get; set; }
    }
}
